---
title: "Data Preparation - R"
author: "Delia Del Aguila"
output: html_document
---

> **Tidy Data**

Tidy data is a standard way of mapping the meaning of a dataset to its structure. A dataset is messy or tidy depending on how rows, columns and tables are matched up with observations, variables and types. 
In tidy data:

1. Each variable forms a column.

2. Each observation forms a row.

3. Each type of observational unit forms a table.

Real datasets can, and often do, violate the three precepts of tidy data in almost every way imaginable. While occasionally you do get a dataset that you can start analyzing immediately, this is the exception, not the rule. Five most common problems with messy datasets, along with their remedies:

1. Column headers are values, not variable names.
 
2. Multiple variables are stored in one column.
 
3. Variables are stored in both rows and columns.
 
4. Multiple types of observational units are stored in the same table.
 
5. A single observational unit is stored in multiple tables.

> **Manipulation** 

Data manipulation includes variable-by-variable transformation (e.g., log or sqrt), as well as aggregation, filtering and reordering. These are the four fundamental verbs of data manipulation:

1. Filter: subsetting or removing observations based on some condition.

2. Transform: adding or modifying variables. These modifications can involve either a single variable (e.g., log-transformation), or multiple variables (e.g., computing density from weight and volume).

3. Aggregate: collapsing multiple values into a single value (e.g., by summing or taking means).

4.Sort: changing the order of observations.


```{r setup}
# Manipulating Data using starwars data
library(dplyr)

starwars_s <- select(starwars, name, gender) #select just the columns name and gender from starwars data
head(starwars_s)

starwars_f <- filter(starwars, gender == "female") #select just rows with female as gender value
head(starwars_f)

#Create new column variables based on existing ones
starwars_nw <- mutate(starwars, mass = mass * 2.205, 
                      heightcat = ifelse(height > 180, "tall", "short"),
                      eye_color = ifelse(eye_color %in% c("black", "blue", "brown"),eye_color,"other"),
                      height = ifelse(height < 75 | height > 200,NA,height))




```


